spring:
  main:
    banner-mode: off
  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:~/development/data/h2/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate # none, create, create-drop, update, validate

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
